import { IconBaseType } from "../../types/icons.types";

export interface UntitledIntegrationIconProps extends IconBaseType {
    integration: eBrowserNames | eCodingPlatforms | eDesignPlatforms | eFinance | eMessengers | eMusic | eOSNames | eOtherIntegrations | eProductivity | eSocialIntegrations | eVideoIntegrations;
}


export enum eBrowserNames {
    CHROME = "chrome",
    EDGE = "edge",
    FIREFOX = "firefox",
    IE = "ie",
    OPERA = "opera",
    SAFARI = "safari",
    TOR = "tor",
    UC = "uc",
    YANDEX = "yandex"
}

export enum eCodingPlatforms {
    ADOBE_DREAMWEAVER = "adobe_dreamweaver",
    ANGULAR = "angular",
    ATOM = "atom",
    BITBUCKET = "bitbucket",
    C_SHARP = "c_sharp",
    C_PLUS_PLUS = "c_plus_plus",
    CODEPEN = "codepen",
    CSS_3 = "css_3",
    DOCKER = "docker",
    DRUPAL = "drupal",
    GIT = "git",
    GO = "go",
    HTML_5 = "html_5",
    JAVA = "java",
    JB_APPCODE = "jb_appcode",
    JB_CLION = "jb_clion",
    JB_DATAGRIP = "jb_datagrip",
    JB_DOTCOVER = "jb_dotcover",
    JB_DOTMEMORY = "jb_dotmemory",
    JB_DOTPEEK = "jb_dotpeek",
    JB_DOTTRACE = "jb_dottrace",
    JB_GOLAND = "jb_goland",
    JB_HUB = "jb_hub",
    JB_INTELLIJ = "jb_intellij",
    JB_KOTLIN = "jb_kotlin",
    JB_PHPSTORM = "jb_phpstorm",
    JB_PYCHARM = "jb_pycharm",
    JB_PYCHARM_EDU = "jb_pycharm_edu",
    JB_RESHARPER = "jb_resharper",
    JB_RESHARPER_C_PLUS_PLUS = "jb_resharper_c_plus_plus",
    JB_RIDER = "jb_rider",
    JB_RUBYMINE = "jb_rubymine",
    JB_TEAMCITY = "jb_teamcity",
    JB_TOOLBOX_APP = "jb_toolbox_app",
    JB_UPSOURCE = "jb_upsource",
    JB_WEBSTORM = "jb_webstorm",
    JB_YOUTRACK = "jb_youtrack",
    JOOMLA = "joomla",
    JQUERY = "jquery",
    JS = "js",
    NODE_JS = "node_js",
    NPM = "npm",
    PHP = "php",
    PYTHON = "python",
    R_LANG = "r_lang",
    REACT = "react",
    REDUX = "redux",
    SUBLIME_TEXT = "sublime_text",
    SWIFT = "swift",
    VS_CODE = "vs_code",
    VUE = "vue",
    WEEBLY = "weebly",
    WORDPRESS = "wordpress",
    YII_1 = "yii_1"
}

export enum eDesignPlatforms {
    ADOBE = "adobe",
    ADOBE_AFTER_EFFECTS = "adobe_after_effects",
    ADOBE_ILLUSTRATOR = "adobe_illustrator",
    ADOBE_INDESIGN = "adobe_indesign",
    ADOBE_LIGHTROOM = "adobe_lightroom",
    ADOBE_PHOTOSHOP = "adobe_photoshop",
    ADOBE_XD = "adobe_xd",
    AUTODESK = "autodesk",
    BEHANCE = "behance",
    DRIBBLE = "dribble",
    FIGMA = "figma",
    FRAMER = "framer",
    INVISION = "invision",
    MARVEL = "marvel",
    PROCREATE = "procreate",
    SKETCH = "sketch",
    ZEPLIN = "zeplin"
}

export enum eFinance {
    ALFA_BANK = "alfa_bank",
    AMERICAN_EXPRESS = "american_express",
    DIRECT_DEBIT = "direct_debit",
    JCB = "jcb",
    MASTERCARD = "mastercard",
    PAYPAL = "paypal",
    QIWI = "qiwi",
    SBERBANK = "sberbank",
    SHOPIFY = "shopify",
    STRIPE = "stripe",
    SWIFT_BANK = "swift_bank",
    TINKOFF = "tinkoff",
    VISA = "visa",
    WEBMONEY = "webmoney",
    WESTERN_UNION = "western_union",
    WORLD_PAY = "world_pay",
    YANDEX_KASSA = "yandex_kassa"
}

export enum eMessengers {
    DISCORD = "discord",
    FACETIME = "facetime",
    FB_MESSENGER = "fb_messenger",
    GOOGLE_MEET = "google_meet",
    GOOGLE_HANGOUTS = "google_hangouts",
    KAKAO_TALK = "kakao_talk",
    LINE = "line",
    MESSAGES = "messages",
    MS_SKYPE = "ms_skype",
    SLACK = "slack",
    SPECTRUM = "spectrum",
    TELEGRAM = "telegram",
    VIBER = "viber",
    WECHAT = "wechat",
    WHATSAPP = "whatsapp",
    ZOOM = "zoom"
}

export enum eMusic {
    APPLE_MUSIC = "apple_music",
    GOOGLE_PLAY_MUSIC = "google_play_music",
    GROOVESHARK = "grooveshark",
    SHAZAM = "shazam",
    SOUND_CLOUD = "sound_cloud",
    SPOTIFY = "spotify",
    YANDEX_MUSIC = "yandex_music",
    YOUTUBE_MUSIC = "youtube_music"
}

export enum eOSNames {
    ANDROID = "android",
    APPLE = "apple",
    BLACKBERRY = "blackberry",
    CHROME_OS = "chrome_os",
    ELEMENTARY = "elementary",
    FEDORA = "fedora",
    FREEBSD = "freebsd",
    GNOME = "gnome",
    IOS = "ios",
    LINUX = "linux",
    LINUX_MINT = "linux_mint",
    MACOS = "macos",
    MICROSOFT = "microsoft",
    UBUNTU = "ubuntu"
}

export enum eOtherIntegrations {
    AIRBNB = "airbnb",
    AMD = "amd",
    ANGEL_LIST = "angel_list",
    APP_STORE = "app_store",
    BLUETOOTH = "bluetooth",
    DELL = "dell",
    ENVATO = "envato",
    GENERAL_ELECTRIC = "general_electric",
    GOOGLE = "google",
    GOOGLE_ADS = "google_ads",
    GOOGLE_PLAY = "google_play",
    IBM = "ibm",
    INTEL = "intel",
    KICKSTARTER = "kickstarter",
    MEDIUM = "medium",
    MS_XBOX = "ms_xbox",
    PLAYSTATION = "playstation",
    PRODUCT_HUNT = "product_hunt",
    STEAM = "steam",
    STUMBLE_UPON = "stumble_upon",
    TECH_CRUNCH = "tech_crunch",
    TRIPADVISOR = "tripadvisor"
}

export enum eProductivity {
    AMAZON = "amazon",
    ASANA = "asana",
    ATLASSIAN = "atlassian",
    BAMBOO = "bamboo",
    BASECAMP = "basecamp",
    CONFLUENCE = "confluence",
    DROPBOX = "dropbox",
    EVERNOTE = "evernote",
    FINDER = "finder",
    FLOWMAPP = "flowmapp",
    G_CALENDAR = "g_calendar",
    GITHUB = "github",
    GITLAB = "gitlab",
    GMAIL = "gmail",
    GOOGLE_DOCS = "google_docs",
    GOOGLE_MAPS = "google_maps",
    GOOGLE_DRIVE = "google_drive",
    GOOGLE_MEET2 = "google_meet2",
    INTERCOM = "intercom",
    JIRA = "jira",
    JIRA_CORE = "jira_core",
    JIRA_OPS = "jira_ops",
    JIRA_SERVICE_DESK = "jira_service_desk",
    KAYAKO = "kayako",
    LINEAR = "linear",
    LOOM = "loom",
    MAILCHIMP = "mailchimp",
    MS_EXCEL = "ms_excel",
    MS_ONEDRIVE = "ms_onedrive",
    MS_OUTLOOK = "ms_outlook",
    MS_POWERPOINT = "ms_powerpoint",
    MS_SHAREPOINT = "ms_sharepoint",
    MS_WORD = "ms_word",
    MS_YAMMER = "ms_yammer",
    NOTION = "notion",
    OPSGENIE = "opsgenie",
    SOURCETREE = "sourcetree",
    TEAMS = "teams",
    THINGS = "things",
    TREEHOUSE = "treehouse",
    TRELLO = "trello",
    WORKFLOWY = "workflowy",
    ZAPIER = "zapier",
    ZENDESK = "zendesk"
}

export enum eSocialIntegrations {
    ASKFM = "askfm",
    BADOO = "badoo",
    FACEBOOK = "facebook",
    FOURSQUARE = "foursquare",
    INSTAGRAM = "instagram",
    LINKEDIN = "linkedin",
    OK = "ok",
    PATREON = "patreon",
    PINTEREST = "pinterest",
    QUORA = "quora",
    QZONE = "qzone",
    REDDIT = "reddit",
    SNAPCHAT = "snapchat",
    STACK_OVERFLOW = "stack_overflow",
    TIKTOK = "tiktok",
    TINDER = "tinder",
    TUMBLR = "tumblr",
    TWITTER = "twitter",
    VK = "vk",
    WEIBO = "weibo"
}

export enum eVideoIntegrations {
    APPEARIN = "appearin",
    COUB = "coub",
    FLICKR = "flickr",
    IGTV = "igtv",
    NETFLIX = "netflix",
    TWITCH = "twitch",
    VIMEO = "vimeo",
    YOUTUBE = "youtube"
}

export enum eAllIntegrations {
    // browsers
    CHROME = "chrome",
    EDGE = "edge",
    FIREFOX = "firefox",
    IE = "ie",
    OPERA = "opera",
    SAFARI = "safari",
    TOR = "tor",
    UC = "uc",
    YANDEX = "yandex",

    // coding
    ADOBE_DREAMWEAVER = "adobe_dreamweaver",
    ANGULAR = "angular",
    ATOM = "atom",
    BITBUCKET = "bitbucket",
    C_SHARP = "c_sharp",
    C_PLUS_PLUS = "c_plus_plus",
    CODEPEN = "codepen",
    CSS_3 = "css_3",
    DOCKER = "docker",
    DRUPAL = "drupal",
    GIT = "git",
    GO = "go",
    HTML_5 = "html_5",
    JAVA = "java",
    JB_APPCODE = "jb_appcode",
    JB_CLION = "jb_clion",
    JB_DATAGRIP = "jb_datagrip",
    JB_DOTCOVER = "jb_dotcover",
    JB_DOTMEMORY = "jb_dotmemory",
    JB_DOTPEEK = "jb_dotpeek",
    JB_DOTTRACE = "jb_dottrace",
    JB_GOLAND = "jb_goland",
    JB_HUB = "jb_hub",
    JB_INTELLIJ = "jb_intellij",
    JB_KOTLIN = "jb_kotlin",
    JB_PHPSTORM = "jb_phpstorm",
    JB_PYCHARM = "jb_pycharm",
    JB_PYCHARM_EDU = "jb_pycharm_edu",
    JB_RESHARPER = "jb_resharper",
    JB_RESHARPER_C_PLUS_PLUS = "jb_resharper_c_plus_plus",
    JB_RIDER = "jb_rider",
    JB_RUBYMINE = "jb_rubymine",
    JB_TEAMCITY = "jb_teamcity",
    JB_TOOLBOX_APP = "jb_toolbox_app",
    JB_UPSOURCE = "jb_upsource",
    JB_WEBSTORM = "jb_webstorm",
    JB_YOUTRACK = "jb_youtrack",
    JOOMLA = "joomla",
    JQUERY = "jquery",
    JS = "js",
    NODE_JS = "node_js",
    NPM = "npm",
    PHP = "php",
    PYTHON = "python",
    R_LANG = "r_lang",
    REACT = "react",
    REDUX = "redux",
    SUBLIME_TEXT = "sublime_text",
    SWIFT = "swift",
    VS_CODE = "vs_code",
    VUE = "vue",
    WEEBLY = "weebly",
    WORDPRESS = "wordpress",
    YII_1 = "yii_1",

    // design
    ADOBE = "adobe",
    ADOBE_AFTER_EFFECTS = "adobe_after_effects",
    ADOBE_ILLUSTRATOR = "adobe_illustrator",
    ADOBE_INDESIGN = "adobe_indesign",
    ADOBE_LIGHTROOM = "adobe_lightroom",
    ADOBE_PHOTOSHOP = "adobe_photoshop",
    ADOBE_XD = "adobe_xd",
    AUTODESK = "autodesk",
    BEHANCE = "behance",
    DRIBBLE = "dribble",
    FIGMA = "figma",
    FRAMER = "framer",
    INVISION = "invision",
    MARVEL = "marvel",
    PROCREATE = "procreate",
    SKETCH = "sketch",
    ZEPLIN = "zeplin",

    // finance
    ALFA_BANK = "alfa_bank",
    AMERICAN_EXPRESS = "american_express",
    DIRECT_DEBIT = "direct_debit",
    JCB = "jcb",
    MASTERCARD = "mastercard",
    PAYPAL = "paypal",
    QIWI = "qiwi",
    SBERBANK = "sberbank",
    SHOPIFY = "shopify",
    STRIPE = "stripe",
    SWIFT_BANK = "swift_bank",
    TINKOFF = "tinkoff",
    VISA = "visa",
    WEBMONEY = "webmoney",
    WESTERN_UNION = "western_union",
    WORLD_PAY = "world_pay",
    YANDEX_KASSA = "yandex_kassa",

    // messengers
    DISCORD = "discord",
    FACETIME = "facetime",
    FB_MESSENGER = "fb_messenger",
    GOOGLE_MEET = "google_meet",
    GOOGLE_HANGOUTS = "google_hangouts",
    KAKAO_TALK = "kakao_talk",
    LINE = "line",
    MESSAGES = "messages",
    MS_SKYPE = "ms_skype",
    SLACK = "slack",
    SPECTRUM = "spectrum",
    TELEGRAM = "telegram",
    VIBER = "viber",
    WECHAT = "wechat",
    WHATSAPP = "whatsapp",
    ZOOM = "zoom",

    // music
    APPLE_MUSIC = "apple_music",
    GOOGLE_PLAY_MUSIC = "google_play_music",
    GROOVESHARK = "grooveshark",
    SHAZAM = "shazam",
    SOUND_CLOUD = "sound_cloud",
    SPOTIFY = "spotify",
    YANDEX_MUSIC = "yandex_music",
    YOUTUBE_MUSIC = "youtube_music",

    // os
    ANDROID = "android",
    APPLE = "apple",
    BLACKBERRY = "blackberry",
    CHROME_OS = "chrome_os",
    ELEMENTARY = "elementary",
    FEDORA = "fedora",
    FREEBSD = "freebsd",
    GNOME = "gnome",
    IOS = "ios",
    LINUX = "linux",
    LINUX_MINT = "linux_mint",
    MACOS = "macos",
    MICROSOFT = "microsoft",
    UBUNTU = "ubuntu",

    // others
    AIRBNB = "airbnb",
    AMD = "amd",
    ANGEL_LIST = "angel_list",
    APP_STORE = "app_store",
    BLUETOOTH = "bluetooth",
    DELL = "dell",
    ENVATO = "envato",
    GENERAL_ELECTRIC = "general_electric",
    GOOGLE = "google",
    GOOGLE_ADS = "google_ads",
    GOOGLE_PLAY = "google_play",
    IBM = "ibm",
    INTEL = "intel",
    KICKSTARTER = "kickstarter",
    MEDIUM = "medium",
    MS_XBOX = "ms_xbox",
    PLAYSTATION = "playstation",
    PRODUCT_HUNT = "product_hunt",
    STEAM = "steam",
    STUMBLE_UPON = "stumble_upon",
    TECH_CRUNCH = "tech_crunch",
    TRIPADVISOR = "tripadvisor",

    // productivity
    AMAZON = "amazon",
    ASANA = "asana",
    ATLASSIAN = "atlassian",
    BAMBOO = "bamboo",
    BASECAMP = "basecamp",
    CONFLUENCE = "confluence",
    DROPBOX = "dropbox",
    EVERNOTE = "evernote",
    FINDER = "finder",
    FLOWMAPP = "flowmapp",
    G_CALENDAR = "g_calendar",
    GITHUB = "github",
    GITLAB = "gitlab",
    GMAIL = "gmail",
    GOOGLE_DOCS = "google_docs",
    GOOGLE_MAPS = "google_maps",
    GOOGLE_DRIVE = "google_drive",
    GOOGLE_MEET2 = "google_meet2",
    INTERCOM = "intercom",
    JIRA = "jira",
    JIRA_CORE = "jira_core",
    JIRA_OPS = "jira_ops",
    JIRA_SERVICE_DESK = "jira_service_desk",
    KAYAKO = "kayako",
    LINEAR = "linear",
    LOOM = "loom",
    MAILCHIMP = "mailchimp",
    MS_EXCEL = "ms_excel",
    MS_ONEDRIVE = "ms_onedrive",
    MS_OUTLOOK = "ms_outlook",
    MS_POWERPOINT = "ms_powerpoint",
    MS_SHAREPOINT = "ms_sharepoint",
    MS_WORD = "ms_word",
    MS_YAMMER = "ms_yammer",
    NOTION = "notion",
    OPSGENIE = "opsgenie",
    SOURCETREE = "sourcetree",
    TEAMS = "teams",
    THINGS = "things",
    TREEHOUSE = "treehouse",
    TRELLO = "trello",
    WORKFLOWY = "workflowy",
    ZAPIER = "zapier",
    ZENDESK = "zendesk",

    // social
    ASKFM = "askfm",
    BADOO = "badoo",
    FACEBOOK = "facebook",
    FOURSQUARE = "foursquare",
    INSTAGRAM = "instagram",
    LINKEDIN = "linkedin",
    OK = "ok",
    PATREON = "patreon",
    PINTEREST = "pinterest",
    QUORA = "quora",
    QZONE = "qzone",
    REDDIT = "reddit",
    SNAPCHAT = "snapchat",
    STACK_OVERFLOW = "stack_overflow",
    TIKTOK = "tiktok",
    TINDER = "tinder",
    TUMBLR = "tumblr",
    TWITTER = "twitter",
    VK = "vk",
    WEIBO = "weibo",

    // video
    APPEARIN = "appearin",
    COUB = "coub",
    FLICKR = "flickr",
    IGTV = "igtv",
    NETFLIX = "netflix",
    TWITCH = "twitch",
    VIMEO = "vimeo",
    YOUTUBE = "youtube"
}